import type { Metadata } from "next";
import { anybody } from "./fonts";
import "./globals.css";
import NavBar from "@/components/navigation/navBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      
      <body className={anybody.className}>   

      <NavBar />
      {children}
      </body>
    </html>
  );
}
