import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Anybody, Arapey} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navigation/navBar";

const inter = Inter({ subsets: ["latin"] });

const anybody = Anybody({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
const arapey = Arapey({
  weight: ['400'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anybody.className}>   
      <NavBar/>
      {children}
      </body>
    </html>
  );
}
