import type { Metadata } from "next";
import { anybody } from "./fonts";
import "./globals.css";
import NavBar from "@/components/navigation/navBar";
import { checkUserLoggedIn } from "../utils/auth";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const hello = checkUserLoggedIn();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anybody.className}>   
      <NavBar />
      {children}
      </body>
    </html>
  );
}
